Sure, here's the contents for the file: /docker-project/docker-project/environment.yml

name: docker-project
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - -r requirements.txt