version: '3'

services:
  web:
    build:
      context: ../..
      dockerfile: src/web/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../../secrets:/app/secrets
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped